pub mod query_log;
pub mod pattern_analyzer;
pub mod query_parser;
pub mod column_tracker;
pub mod time_analyzer;
pub mod query_fingerprinter;
pub mod join_analyzer;
pub mod cost_calculator;
pub mod anomaly_detector;
pub mod export;
pub mod existing_index_checker;
pub mod index_usage_simulator;
pub mod partial_index_recommender;
pub mod index_maintenance_cost;
pub mod priority_scoring;
pub mod index_removal_recommender;
pub mod query_plan_analyzer;
pub mod schema_optimizer;
pub mod performance_monitor;
pub mod deadlock_detector;

pub use query_log::QueryLog;
pub use pattern_analyzer::{PatternAnalyzer, QueryPattern};
pub use query_parser::{QueryParser, ParsedQuery};
pub use column_tracker::{ColumnTracker, ColumnUsage};
pub use time_analyzer::{TimeAnalyzer, TimePattern};
pub use query_fingerprinter::{QueryFingerprinter, QueryFingerprint};
pub use join_analyzer::{JoinAnalyzer, JoinPattern};
pub use cost_calculator::{CostCalculator, QueryCost};
pub use anomaly_detector::{AnomalyDetector, AnomalyResult};
pub use export::DataExporter;
pub use existing_index_checker::{ExistingIndexChecker, ExistingIndex, IndexConflict};
pub use index_usage_simulator::{IndexUsageSimulator, IndexSimulation};
pub use partial_index_recommender::{PartialIndexRecommender, PartialIndexRecommendation};
pub use index_maintenance_cost::{IndexMaintenanceCostAnalyzer, MaintenanceCost};
pub use priority_scoring::{PriorityScoringAlgorithm, PriorityScore};
pub use index_removal_recommender::{IndexRemovalRecommender, IndexUsageStats, RemovalRecommendation};
pub use query_plan_analyzer::{QueryPlanAnalyzer, QueryPlan, PlanOperation};
pub use schema_optimizer::{SchemaOptimizer, TableSchema, ColumnInfo, SchemaOptimization};
pub use performance_monitor::{PerformanceMonitor, PerformanceMetric, PerformanceAlert};
pub use deadlock_detector::{DeadlockDetector, DeadlockInfo, DeadlockPrevention};